name: PHP Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List PHP files
      run: find . -name "*.php"

    - name: Run PHP lint
      run: |
        set -e
        find . -name "*.php" -exec php -l {} \; # Verifica errores de sintaxis
