name: PHP Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List PHP files
      run: find . -name "*.php"

    - name: Run PHP lint
      run: |
        set -e
        files=$(find . -name "*.php")
        if [ -z "$files" ]; then
          echo "No PHP files found."
          exit 1
        fi
        for file in $files; do
          php -l $file
          if [ $? -ne 0 ]; then
            echo "Syntax error in $file"
            exit 1
          fi
        done
